### ISSUE TITLE
Add repoHostname Field

### ISSUE THREAD

**Issue by lukad03** [GSA/code-gov-api#1]
Add a repoHostname field to determine the host of the repo (i.e. GitHub, Bitbucket). This will be useful for the front-end as it will enable custom iconography to be introduced from FontAwesome or other sources to display the logo of the repo host wherever the repo is displayed.

**Comment by froi** [comment]
@DanielJDufour any thoughts on this. I'm inclined to close it.

**Comment by saracope** [comment]
Closing out as this is not in our current roadmap.
