### ISSUE TITLE
Employ api.data.gov for API keys and analytics

### ISSUE THREAD

**Issue by gbinal** [GSA/code-gov-api#134]
The [api.data.gov](https://api.data.gov/about) shared service is set up for use here at GSA and there's a general push to try and get all of our agency's APIs using it.  The main functionalities to using it are: 
* provides api key management (example signup form [here](http://gsa.github.io/sam_api/sam/key))
* provides robust api analytics (e.g. who is using the api, how are they using it, how much, etc)
* create usage tiers for privileged users
* makes it easier to update and maintain the API in the future by having the api.data.gov url serve as a platform underneath which you can do work.  

We can easily set up something either like `https://api.gsa.gov/code/` or `https://api.code.gov/` for you to try without any effort.  Holler if you have any questions or want to set up a time to demo this others on the team.  

Regardless, I really recommend ensuring that you've got API analytics set up.  Doing that before you roll out the API publicly also saves a lot of time in the long run.

**Comment by froi** [comment]
Thanks @gbinal. This looks really cool. Just talked to the team and we would like to take this for a spin. We'd like to use api.code.gov. Let's get together and hash this out.

**Comment by gbinal** [comment]
Great!  That's easy to do.  


The next step we should follow is setting up api.code.gov.  This can be done by filling out an IT service desk ticket asking for `api.code.gov` to be CNAMED to `api-code-gov.domains.api.data.gov`.  @froi - Do you want to do this or do you want me to?  I'm cool with either.  

Here's some more detail about the why's and how's of using your own domain: https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies#using-your-own-domain-name

We can handle HTTPS setup, so there shouldn't be much else involved beyond getting the CNAME record setup.

**Comment by gbinal** [comment]
One update.  It looks like I was wrong and the means by which to we need to set up this CNAME is through https://github.com/18F/dns (more info [here](https://github.com/18F/dns#making-changes)), and not through filing a ticket with GSA IT.  

I'm going to create a PR - https://github.com/18F/dns/pull/162.  

@froi - if someone on your team is familiar with the [DNS setup for code.gov](https://github.com/18F/dns/blob/deploy/terraform/code.gov.tf)), it'd be good to get a review of that PR.

**Comment by froi** [comment]
Hi @gbinal. Thanks for this! I'll see who has the keys to that kingdom and see what I can do with that.

**Comment by gbinal** [comment]
Alright - we're good.  

https://api.code.gov/0.1/agencies?api_key=lX6zhADaBByrxGyDWaskPGhGGWFt6GiBQXdQ8wNl

You should have admin access over in https://api.data.gov/admin.  Holler with who else you'd like to give access and if you'd like a demo and walk-through.

**Comment by froi** [comment]
Freaking amazing. Thank you so much!!!!
