### ISSUE TITLE
Use the GSA API documentation template

### ISSUE THREAD

**Issue by gbinal** [GSA/code-gov-api#135]
An [increasing](http://gsa.github.io/sam_api/sam/) [number](http://gsa.github.io/eMuseum-API/) [of](https://gsa.github.io/DSSAPIDocumentation/api-docs/) [GSA](http://gsa.github.io/auctions_api/) APIs are normalizing around the user of [this opensource API template](https://github.com/GSA/api-documentation-template).  

It'd be very easy to stand up an new instance for this API and use it for the API docs (I'm happy to help with it).  And adopting this not only makes for good looking api docs, but also helps the agency put forward a more consistent, developer-friendly experience.

**Comment by froi** [comment]
We've created [code-gov-developer-docs](https://github.com/GSA/code-gov-developer-docs). We are currently waiting for the Federalist support team to scan and approve the site.
