### ISSUE TITLE
Add ability to sort agencies

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#165]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

Want to be able to sort agencies alphabetically

## Current Behavior

Can't sort

## Possible Solution

Add sorting capability to API endpoint

## Context

Would like agencies sorted for displaying in alphabetical order in agency sidebar

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate API with Search #Sprint_19 #Sprint_22 #Sprint_23 #Sprint_24](https://trello.com/c/Iphow2ev/453-integrate-api-with-search-sprint19-sprint22-sprint23)

**Comment by DanielJDufour** [comment]
I'm setting to low priority because I can do client side sorting and I'm getting all the agencies anyway, so sorting wouldn't reduce network traffic
