### ISSUE TITLE
Terms Endpoint in Staging Env Returning Error

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#173]
## Expected Behavior

Should return JSON

## Current Behavior

Returning internal server error

## Steps to Reproduce (for bugs)

1. go to {{staing_url}}/api/0.1/terms?term=Soc&size=5&term_type=agency.acronym&term_type=agency.name

## Context

Can't have landing/home page with search work without it

**Comment by froi** [comment]
Confirming error:

![image](https://user-images.githubusercontent.com/1918027/35878194-84c4ad6a-0b45-11e8-9182-e0bb763d5104.png)

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Terms Endpoint in Staging Env Returning Error](https://trello.com/c/U2wacxT6/586-terms-endpoint-in-staging-env-returning-error)
