### ISSUE TITLE
Agencies Endpoint Only Returning 12 Agencies

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#177]
## Expected Behavior

I'd expect more agencies to be returned.

## Current Behavior

Only 12 are returned

## Possible Solution

Not sure

## Steps to Reproduce (for bugs)

1. go to https://code-api-staging.app.cloud.gov/api/0.1/agencies

## Context

I'm confused.  This may be working correctly and I have just misunderstood something.

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Agencies Endpoint in Staging Env Returning Error](https://trello.com/c/KmbYZfI8/584-agencies-endpoint-in-staging-env-returning-error)

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Agencies Endpoint Only Returning 12 Agencies](https://trello.com/c/SfuttjGC/585-agencies-endpoint-only-returning-12-agencies)

**Comment by froi** [comment]
The endpoint is functioning as expected. The issue seems to be in how the API is indexing the agencies.
