### ISSUE TITLE
Not Gettings Agencies for Some Acronyms on Staging

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#178]
## Expected Behavior

Expect array of repos

## Current Behavior

Get empty array

## Possible Solution

Not sure. Run harvester??

## Steps to Reproduce (for bugs)

1. Go to https://code-api-staging.app.cloud.gov/api/0.1/repos?agency.acronym=NASA
2. Got to https://code-api-staging.app.cloud.gov/api/0.1/repos?agency.acronym=USAID

## Context

I might be wrong and this is just a result of the staging environment not having all the data as production.  Would still be helpful if data in staging matched what will be in production as much as possible.

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Not Gettings Agencies for Some Acronyms on Staging](https://trello.com/c/fwKoVFHI/583-not-gettings-agencies-for-some-acronyms-on-staging)
