### ISSUE TITLE
Can't filter by multiple usage types

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#179]
## Expected Behavior

Should be able to get all repos for an agency that are open source or government wide reuse

## Current Behavior

Internal Server Error when try to filter by both at the same time.  The repos endpoint works when try to filter by only one.

## Possible Solution

Not sure.  Can I assume that all the repos returned from the repos endpoint are either governmentWideReuse or openSource and never exempt?

## Steps to Reproduce (for bugs)

1. https://code-api-staging.app.cloud.gov/api/0.1/repos?agency.acronym=GSA&size=1000&permissions.usageType=openSource&permissions.usageType=governmentWideReuse

## Context

Need this in order to show repos for an agency on code.gov while not showing exempt repos.

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can't filter by multiple usage type](https://trello.com/c/IwFIIO7J/582-cant-filter-by-multiple-usage-type)

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate API with Search #Sprint_19 #Sprint_22 #Sprint_23 #Sprint_24](https://trello.com/c/Iphow2ev/453-integrate-api-with-search-sprint19-sprint22-sprint23)
