### ISSUE TITLE
Swagger Docs on Staging for Repos Endpoint not Showing Params

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#180]
## Expected Behavior

Should see params like agency.acronym, size and permissions.usageType

## Current Behavior

Swagger says "no parameters"
![image](https://user-images.githubusercontent.com/4313463/35930419-d6428b34-0bff-11e8-8aa1-1d0ac7171e50.png)

## Possible Solution

 Update Swagger Docs?

## Steps to Reproduce (for bugs)

1. Go to https://code-api-staging.app.cloud.gov/api-docs/#/repo/get_repos

## Context

Makes filtering repos confusing.  I'd like to see info about sorting param.

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Swagger docs](https://trello.com/c/b4mi7jJ2/569-fix-swagger-docs)

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Swagger docs](https://trello.com/c/1PbPyyz2/580-fix-swagger-docs)

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Swagger docs](https://trello.com/c/1PbPyyz2/580-fix-swagger-docs)
