### ISSUE TITLE
Agencies/AgencyAcronym Endpoint

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#188]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

It'd be great if I could get an agency the same way I get a repo like `agencies/{{agencyAcronym}}`

## Current Behavior

Can't filter agency endpoint

## Context

Would be great if I could filter the agencies endpoint by agency acronym because there's parts in the code where this would be helpful.  If I only need to get information for one agency, I'd prefer to not have to get it for all of them and then filter it.

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate API with Search #Sprint_19 #Sprint_22 #Sprint_23 #Sprint_24](https://trello.com/c/Iphow2ev/453-integrate-api-with-search-sprint19-sprint22-sprint23)

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a agency detail endpoint](https://trello.com/c/ha0vEmjp/645-add-a-agency-detail-endpoint)
