### ISSUE TITLE
Filter search by multiple usage type

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#192]
## Expected Behavior

Would like to only get search results that are open source or government wide reuse. Would like exempt excluded.

## Current Behavior

Can't filter. Have to filter client side.

## Possible Solution

Add filtering option for api, but have to filter by multiple permissions type 

## Steps to Reproduce (for bugs)

1. go to https://code-api.app.cloud.gov/api/repos?q=freespace%20simulation%20environment&permissions.usageType=governmentWideReuse&permissions.usageType=openSource&size=100

## Context

Low priority. Wrote some code that does client side filtering.  Solving this issue on the backend would probably improve performance by less then 10%.  That being said, we shouldn't be returning the exempt repos via the API even if no one sees them.  It should also be noted that exempt repos are in the code.jsons.

**Comment by froi** [comment]
This issue has been resolved from release v2.0.1 onwards.
