### ISSUE TITLE
Add id Field in Conjunction with the repoID

### ISSUE THREAD

**Issue by lukad03** [GSA/code-gov-api#2]
Add a numeric id field that we can guarantee is unique. The front-end is currently using the repoID to resolve the repo's route. To make the switch over to a different field without having to create redirects in the front-end, I propose we create an id field which matches the repoID unless that id already exists in the API - in which case a new, randomly generated unique number be created and saved as the id of the repo for the API's purposes.

**Comment by froi** [comment]
Closed for inactivity.
