### ISSUE TITLE
Consistent Time for Data Harvesting 

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-api#204]
The DOI-USGS CIO office has completed a NodeJS base app that they plan to run on the daily basis to automatically generate updates to their code.json software inventory from their subversion control systems.

USGS would like to know the time in which the Code.gov API executes the data harvesting process. And they would like it to be set to a specific time in the day.

**Comment by froi** [comment]
We will not be adding any scheduling functionality to the API. This is more of a Code.gov operations topic and not a feature that should be added to the project.

I'm closing this issue and moving all discussion to our internal ops board.
