### ISSUE TITLE
API Developers URL 

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-api#206]
@froi 
I've noticed that most organizations that have an API Developer service use developer.domain.com on their documentation URL, singular, not plural as their standard.
 
For example:
https://developer.apple.com
https://developer.github.com
https://developers.facebook.com
https://developer.twitter.com

Except, Google uses https://developers.google.com.

However, Google has a redirect on https://developer.google.com to https://developers.google.com

I was wondering if you plan to create a redirect on https://developer.code.gov to point to https://developers.code.gov

**Comment by DanielJDufour** [comment]
I'm deferring to @froi on this

**Comment by saracope** [comment]
No plans to put this in the roadmap, closing out.
