### ISSUE TITLE
Schema Validation (as a service)

### ISSUE THREAD

**Issue by arichiv** [GSA/code-gov-api#225]
It would be nice to have schema validation as a service. https://code.gov/#/policy-guide/docs/compliance/inventory-code/tools/validate-schema provides a GUI, but a CLI interface would be great for automating our deployment system (to ensure our JSON is valid).

One possible interface:

https://api.code.gov/validate-schema&version=2.0.0&uri=https://...
Can return a 200 with no errors, or a 400 with a JSON list of errors

**Comment by froi** [comment]
[Something like this](https://github.com/GSA/code-gov-data/tree/master/schemas) @jbjonesjr ?
