### ISSUE TITLE
Filter Repos by Multiple Agencies

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#244]
**Is your feature request related to a problem? Please describe.**
I'm working on the browse projects page.  It's slow to load because I'm loading all the repos in the browser first and then doing all the filtering client side.

**Describe the solution you'd like**
I'd like to be able to filter by multiple agencies.

**Describe alternatives you've considered**
I could have a really nice loading image.  I could also be typing something in wrong!

**Additional context**
Here's a sample url: https://api.code.gov/repos?api_key=DEMO_KEY&agency.acronym=DOD,NASA
Sample Return:
```
{
  "total": 0,
  "repos": []
}
```

**Comment by froi** [comment]
You can already filter by multiple agencies. You can filter by multiple values of any field by passing the same field in as a parameter multiple time.

Eg.

```bash
curl "https://api.code.gov/repos/?agency.acronym=CFPB&agency.acronym=USDA" \
     -H 'Content-Type: application/json' \
     -H 'X-Api-Key: <your-key>'
```
To use your example:
https://api.code.gov/repos?api_key=DEMO_KEY&agency.acronym=DOD&agency.acronym=NASA

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/1918027/44163452-7a752600-a091-11e8-979c-196dd1572e52.png">

If I'm not mistaken the frontend is already doing this with the `permissions.usageType` field.

**Comment by DanielJDufour** [comment]
Ooops. @froi , you're so right.  I'm closing the issue now.
