### ISSUE TITLE
Add FEC agency to our harvesting process.

### ISSUE THREAD

**Issue by froi** [GSA/code-gov-api#253]
**Describe the solution you'd like**

Add FEC as an agency to have its `code.json` harvested. They do not have to show up in the compliance dashboard.

More details can be found in [https://github.com/GSA/code-gov/issues/16](https://github.com/GSA/code-gov/issues/16).

**Comment by RicardoAReyes** [comment]
https://www.fec.gov/code.json

Code.json is live.

**Comment by froi** [comment]
I'll start adding them to the harvesting process. Thanks

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add FEC to code.gov index](https://trello.com/c/O5qfJlKd/973-add-fec-to-codegov-index)
