### ISSUE TITLE
Filter By License

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#260]
**Is your feature request related to a problem? Please describe.**
I want to load as little unnecessary data as possible when searching for repos.  It'd be ideal to be able to filter by license. 

**Describe the solution you'd like**
add an ability to filter by license.  The tree structure is really weird, so I'm not sure how you want to do the mapping.  Maybe `...&licenses_name=` or `licenses.0.name=...`

**Describe alternatives you've considered**
I can filter client side, but would prefer server side

**Additional context**
Thanks!

**Comment by DanielJDufour** [comment]
I'm making this high priority, because it's the only thing stopping us moving all the display logic (filtering and sorting) of the repositories into the backend, which will speed up performance.

**Comment by DanielJDufour** [comment]
In other words, if I want to fetch ten repositories that have a CCO-1.0 license.  The best way to do that currently is to fetch an absurdly large number like 10k and then filter the result, stopping once I reach 10.

**Comment by DanielJDufour** [comment]
@froi , would it also be possible to normalize the license values.  Happy to talk about this more later, but basically the idea is that if someone puts in a spdx-identifier or the full name in the name field.  It should still catch is when I filter.

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Filter by License](https://trello.com/c/m6wHHbw9/1076-filter-by-license)
