### ISSUE TITLE
Fix NSA's codeURL

### ISSUE THREAD

**Issue by kaitersgonnakait** [GSA/code-gov-api#271]
**Bug Description**
The codeUrl listed for the NSA's code.json results in a 404.

**To Reproduce**
The most recent projects listed on code.gov as published by NSA (https://github.com/nsacyber) are at least a couple years old.

Digging deeper into why the data is out of date when code.gov is supposed to pull code.json files daily -- the /agencies API shows that the URL for the NSA is nsa.gov/code.json, which doesn't exist.  (see screenshot below)
However, https://nsacyber.github.io/code.json does exist.

https://api.code.gov/status/NSA/fetched also gives a 502, but works for other agencies, showing that something is wrong with NSA fetching.

**Expected behavior**
Recent projects should show up as owned by NSA.  Projects at https://github.com/nsacyber should all show up at code.gov.

**Screenshots**
![image](https://user-images.githubusercontent.com/1033621/46057921-38c2ab00-c126-11e8-8f69-d0c094acf67f.png)

**Additional context**
It seems like one remedy is to change the codeURL to https://nsacyber.github.io/code.json.  If NSA actually has multiple sites that host code.json files, then maybe additional agency entries should be added to the metadata file.

**Comment by froi** [comment]
Thank you so much for this! 

Up to now, the official location is been `https://nsa.gov/code.json` and we have not heard from the agency of this change. This location (`https://nsa.gov/code.json`) is the one specified by the Federal Source Code Policy.

I'm cc'ing @RicardoAReyes, who is in contact with our partner agencies. He will follow up on this. If this new URL is to be the official one we will merge your PR #272 and get this closed up.

Again thank you so much for this 😄

**Comment by RicardoAReyes** [comment]
Hi @kaitlin-farr , we love your initiative. 

I have reached out to the NSA Open Source leaders, as well as the DOD (Code.mil) leadership to address the PR. Technically, the [OMB M-16-21 FSCP](http://localhost:2700/#/policy-guide/policy/introduction) requires for the agencies (NSA) to publish their (code.json) file on the national website (https://www.nsa.gov/code.json) for us to harvest.

However, some agencies have created an HTTP 301 redirect from their national website to a GitHub.gov repo code.json file. So the should works as well.  i.e. https://www.nsa.gov/code.json, which NSA could create a redirect to the https://nsacyber.github.io/code.json. 

Also, we are currently harvesting the DOD OSS from the Code.mil website (https://code.mil/code.json), @jakerella supervises the process and intake for the Code.mil/code.json file. 

I have notified the NSA and DOD Open Source leaders to make them aware of your PR. We'll be waiting for their feedback on how to best proceed forward. And hopefully they can respond directly on your PR.

Thank you for your understanding, we look forward to your future collaboration and PRs!

**Comment by kaitlin-farr** [comment]
Thanks for the quick feedback! Hope it gets sorted out soon. Can't wait to hear back!

**Comment by ctubbsii** [comment]
NSA's code.json can be found at https://code.nsa.gov/code.json
