### ISSUE TITLE
Please add USDS to code.gov

### ISSUE THREAD

**Issue by fatima-gov** [GSA/code-gov-api#275]
We are in the process of adding our `code.json` file to usds.gov (we are anticipating this change to happen tomorrow, 10/2). 

After this change, please add USDS to the list of agencies on [agency_metadata_json](https://github.com/GSA/code-gov-api/blob/master/config/agency_metadata.json) for you harvesting process. 

Please let me know if you need anything else!

cc: @RicardoAReyes @froi

**Comment by froi** [comment]
Hi @fatima-gov.

Thanks for posting this issue. I was under the impression that the USDS code.json file would be aggregated under the [EOP-OMB inventory](https://github.com/EOP-OMB/code_json/blob/master/code.json).

I've contacted Larry Lambert, the current maintainer of the code.json, and he's asked me to put you in contact. I will be sending an email to both and once this is resolved will be closing this issue.

Please do not hesitate to contact me or Larry with comments or questions 😄

**Comment by froi** [comment]
@fatima-gov I think it would be best if a PR is made to the [EOP-OMB code.json repository](https://github.com/EOP-OMB/code_json).

cc: @LarryLambert

**Comment by froi** [comment]
Closed issue by mistake.

**Comment by froi** [comment]
The __USDS__ has been added to the EOP-OMB code.json https://github.com/EOP-OMB/code_json/blob/master/code.json#L180-L186
