### ISSUE TITLE
API Calls Not Working for DOE on Chrome

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#276]
**Describe the bug**

**To Reproduce**
See steps here: https://github.com/GSA/code-gov-web/issues/672

**Expected behavior**
API calls should work

**Screenshots**
See https://github.com/GSA/code-gov-web/issues/672

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
Original issue posted here: https://github.com/GSA/code-gov-web/issues/672

**Comment by froi** [comment]
Found the issue. The API gateway was rejecting all requests from `https://www.code.gov/`. The `www` subdomain has been added to the HTTP referer whitelist and is now working.

Before updating the HTTP referer whitelist:
<img width="1291" alt="screenshot 2018-10-06 23 55 51" src="https://user-images.githubusercontent.com/1918027/46578099-e73adb80-c9c3-11e8-8736-ac6fa135c4da.png">

After updating the HTTP referer whitelist:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/1918027/46578096-c6728600-c9c3-11e8-92ab-7dc1fe0daa57.png">
