### ISSUE TITLE
Code.gov Compliance Dashboard Missing Agencies (USDA and DOC)

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-api#278]
@froi the Code.gov Compliance Dashboard is missing two agencies: Department of Agriculture (USDA) and Department of Commerce (DOC).

The API only returns 23 records, not the 24 CFO Act Agencies + NARA. 

**To Reproduce**
1. Go to https://code.gov/#!/policy-guide/docs/compliance/dashboard
2. See the list, USDA and DOC are missing. 
3. Browsing through the Code.gov API REST request: 
https://api.code.gov/agencies?size=1000&api_key=OC457325hyT6DpFm5HBBZ1i8SR6gtp5U2CdqtHZQ
4. JSON total is: 22

**Expected behavior**
USDA and DOC should be represented on the Compliance Dashboard..

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome, Safari, Firefox 

![compliace_issue](https://user-images.githubusercontent.com/2433138/47037398-d4a36d80-d14c-11e8-99b8-57e44ad9f3b2.gif)

**Comment by froi** [comment]
Confirmed. Thanks for the issue, looking into it.

**Comment by froi** [comment]
@RicardoAReyes I verified the issue and found no real indication of an error / bug. I then reran the harvester and validated that expected agencies where indexed and included in the compliancy dashboard. Please see screen shot below.

![image](https://user-images.githubusercontent.com/1918027/47042986-885f2a00-d15a-11e8-8f90-c30e50ebf741.png)

Please confirm that you can see the agencies on your end. Once you confirm this we can close this issue.

Thanks!

**Comment by froi** [comment]
@RicardoAReyes can I get a spot check on this so we can close it? Thanks.

**Comment by RicardoAReyes** [comment]
@froi I have validated the Compliance Dashboard - agency representation looks good!
