### ISSUE TITLE
Languages Filter Breaking Search Results On Rearchitecture Version

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#283]
**Describe the bug**

**To Reproduce**
1. Fetch 'https://api.code.gov/repos?size=100&api_key={{API_KEY_HERE}}&q=gis&permissions.usageType=openSource&permissions.usageType=governmentWideReuse&languages=R'

**Expected behavior**
Should get some repos

**Screenshots**
With languages filter:
![image](https://user-images.githubusercontent.com/4313463/47295507-c9818f00-d5dd-11e8-8ce7-e50d98fb93be.png)
Without languages filter:
![image](https://user-images.githubusercontent.com/4313463/47295532-d8684180-d5dd-11e8-95a1-dd33c85a6b97.png)

**Additional context**
- This is necessary for the re-architecture to work
- This does not break current production because currently filtering is happening on the client-side.

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Language filter breaking search results on rearchitecture version](https://trello.com/c/EEZ7vK2c/1078-language-filter-breaking-search-results-on-rearchitecture-version)
