### ISSUE TITLE
On Staging: Repos without Languages Returned on Language Filter

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-api#297]
**Describe the bug**

**To Reproduce**
1. Go to https://code-api-staging.app.cloud.gov/api/repos?size=10&api_key=DEMO_KEY&agency.acronym=usaid&permissions.usageType=openSource&permissions.usageType=governmentWideReuse&languages=assembly

**Expected behavior**
No repos should be returned because USAID doesn't have any repos with assembly as the language indexed

**Screenshots**
![image](https://user-images.githubusercontent.com/4313463/47972351-53633a80-e069-11e8-8a1a-ef143a44de5d.png)

**Additional context**
This is necessary before migration.

**Comment by DanielJDufour** [comment]
@froi , I would prefer if there are no repos that match the return that a JSON without any repos is returned, as is currently being done on the production API
![image](https://user-images.githubusercontent.com/4313463/48009105-fb6c1880-e0e8-11e8-89b8-f2397b7e18aa.png)

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [API Repo search should return an empty collection when no repos are found with a filter](https://trello.com/c/l31lHu8u/1101-api-repo-search-should-return-an-empty-collection-when-no-repos-are-found-with-a-filter)

**Comment by froi** [comment]
> @froi , I would prefer if there are no repos that match the return that a JSON without any repos is returned, as is currently being done on the production API
> ![image](https://user-images.githubusercontent.com/4313463/48009105-fb6c1880-e0e8-11e8-89b8-f2397b7e18aa.png)

This has been pushed into staging. Let me know if all is working as expected.
