### ISSUE TITLE
Clean up project

### ISSUE THREAD

**Issue by froi** [GSA/code-gov-api#306]
**Is your feature request related to a problem? Please describe.**

Much of the functionality has been moved to other projects such as the code-gov-harvester, code-gov-adapters, code-gov-integrations, and others. Having all of this move has left this project with unused legacy code that just makes the project harder to maintain that it really should be.

**Describe the solution you'd like**

Do a major code clean up of the project and remove everything that isn't needed anymore.

**Describe alternatives you've considered**

None

**Comment by Nosferican** [comment]
Should this issue be closed?
