### ISSUE TITLE
Elastic search Indexing should use usageType for unique key or Globally Unique Identifier (GUID)

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-api#311]
DOE and SSA have presented Elastic search indexing issue in which repos as seem as duplicate on our platform as false positive. 

DOE (@vowelllDOE, @IanLee1521) has multiple repos with the same title from the same organization version. The Code.gov harvesting process overrides existing repos with the same agency + organization + title to generate a unique key for the index.

Current Code.gov Elastic Search harvesting /indexing process: 
![screen shot 2019-02-26 at 12 56 49 pm](https://user-images.githubusercontent.com/2433138/53435097-0c0d0b00-39c6-11e9-8a21-39c96fc5b089.png)

**DOE Example:**
![doe-duplicate](https://user-images.githubusercontent.com/2433138/53435377-a8371200-39c6-11e9-9440-2fb97e518d5e.png)

DOE has recommended for Code.gov to address this use case scenario. It's my assumption that a potential business case could be for organizations to have one repo as Open Source for public consumption, and an alternative for internal use for production use.  However, the agency has reported both repos since they could differ in source-code. 

**Recommendation 1**: Introduce repo "usageType" as part of the Elastic Search unique key. 
![screen shot 2019-02-26 at 1 07 51 pm](https://user-images.githubusercontent.com/2433138/53435763-92761c80-39c7-11e9-8d94-91a375521ee0.png)

This solution would introduce the usageType on the code.gov repo URL. The solution could have the full **usageType** title or variable such as o = Open Source, g = Government Wide Reuse, e = exempt by x.

**Recommendation 2:**  (long term solution)
@SSAgov (SSA) has recommended that use a [Globally Unique Identifier (GUID)](https://www.npmjs.com/package/uuid) for each repo. The [Code.gov Metadata Schema 2.0.0](https://www.code.gov/about/compliance/inventory-code) should introduce a new property for the agencies to enter a GUID for the repository. 

Related Issue addressing repo duplicate count with agencies. 
https://github.com/GSA/code-gov-api/issues/310

@jcastle @saracope @AminPIC thoughts...?

**Comment by vowelllDOE** [comment]
I think it should also take "name" into consideration for this deduplication.  Many sites uses a single landing page for access to multiple packages of various source codes.  You can see this in the example above with https://ip.sandia.gov/contact.do.  Those two packages are completely different, they just share the same URL.

**Comment by RicardoAReyes** [comment]
@vowelllDOE the process does use the repo name (title) into consideration already. It's variable that is being used to help identify duplicates from the same organization.

**Comment by vowelllDOE** [comment]
@RicardoAReyes then I'm confused how the example you have above is a dupe

**Comment by bjbhatt** [comment]
@RicardoAReyes even after including UsageType for DOE I'm still finding 18 duplicate (e.g. record at position 371 still matches position 260)

**Comment by bjbhatt** [comment]
@vowelllDOE when generating a Unique ID for a repo record, the system currently, as programmed,  uses combination of Agency + Organization + Name  

*Example*: 
agency: DOE
organization: Lawrence Livermore National Laboratory (LLNL)
name: AMPE
Unique Id (generated): doe_lawrence_livermore_national_laboratory_llnl_ampe

**Comment by vowelllDOE** [comment]
@bjbhatt 

Please forgive my ignorance, then how do these duplicate?

![image](https://user-images.githubusercontent.com/20361298/53440577-e5090600-39d2-11e9-8cb3-25b99318fe10.png)

and @RicardoAReyes keeps mentioning the repo url in the dupe check

**Comment by bjbhatt** [comment]
@vowellDOE, I think there is a confusion.  there are two distinct issues.  

1. Unique Key generation: where Agency+Organization+Name matches another record (see record 371 and 260 in your code.json file - zero-based).  This is a technical issue, where the previous record gets overwritten by the newer one.
2. A repositoryURL for an "openSource" project matches another repositoryURL (see record 141 and 129 in your code.json file - zero-based).  This is NOT a technical issue but "should this be the case"

**Comment by vowelllDOE** [comment]
@bjbhatt 

For #2, yes that should be the case.  As described above Many sites uses a single landing page for access to multiple packages of various source codes. You can see this in the example above with https://ip.sandia.gov/contact.do. Those two packages are completely different, they just share the same URL.

**Comment by bjbhatt** [comment]
@vowelllDOE 
#1 - We are talking internally to figure out a solution for generating unique id differently, will keep you posted.
#2 - understood

**Comment by IanLee1521** [comment]
@bjbhatt -- Can you provide a link / list / report of the unique IDs for all of (18 it sounds like?) duplicated `agency+org+repo_name`s ?

**Comment by bjbhatt** [comment]
@IanLee1521  here it is.
[DOE-duplicateName.json.txt](https://github.com/GSA/code-gov-api/files/2910563/DOE-duplicateName.json.txt)

**Comment by bjbhatt** [comment]
This issue is resolved and should be closed @RicardoAReyes @saracope.
