### ISSUE TITLE
add Elasticsearch License Info

### ISSUE THREAD

**Issue by okamanda** [GSA/code-gov-api#96]
Our [license.MD](https://github.com/presidential-innovation-fellows/code-gov-api/blob/master/LICENSE.md) still references MongoDB, which we no longer use. We need to update it to reflect our Elasticsearch usage. @froi Can you add a card in trello for this task? 

Thanks

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Our license.MD still references MongoDB, which we no longer use. We need to update it to reflect our Elasticsearch usage.](https://trello.com/c/ISBbuHlz/281-our-licensemd-still-references-mongodb-which-we-no-longer-use-we-need-to-update-it-to-reflect-our-elasticsearch-usage)

**Comment by froi** [comment]
Closed with PR https://github.com/GSA/code-gov-api/pull/99
